name: DB-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: update submodule
       run: |
          git submodule update --init --recursive

    - name: cmake
      run: cmake .

    -name: cmake build
      run: cmake --build .
